spring:
  datasource:
    url: ${BT_DB_URL}
    username: ${BT_DB_USERNAME}
    password: ${BT_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: sample
    initialization-mode: always