spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/btraining?sslMode=DISABLED
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: sample
    initialization-mode: always