spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/btraining?sslMode=DISABLED
    username: btraining_user
    password: btraining_pass
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: sample
    initialization-mode: always